//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationForCourseClient.RegistrationServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/RegistrationForOOPCourseService.Models")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GradeByBasicsOfAlgorithmsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GradeByBasicsOfAlgorithms {
            get {
                return this.GradeByBasicsOfAlgorithmsField;
            }
            set {
                if ((this.GradeByBasicsOfAlgorithmsField.Equals(value) != true)) {
                    this.GradeByBasicsOfAlgorithmsField = value;
                    this.RaisePropertyChanged("GradeByBasicsOfAlgorithms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegistrationServiceReference.IRegistrationForOOPCourseContract", CallbackContract=typeof(RegistrationForCourseClient.RegistrationServiceReference.IRegistrationForOOPCourseContractCallback))]
    public interface IRegistrationForOOPCourseContract {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRegistrationForOOPCourseContract/Join")]
        void Join();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRegistrationForOOPCourseContract/Join")]
        System.Threading.Tasks.Task JoinAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRegistrationForOOPCourseContract/Leave")]
        void Leave(int id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRegistrationForOOPCourseContract/Leave")]
        System.Threading.Tasks.Task LeaveAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRegistrationForOOPCourseContract/Registration")]
        void Registration(int id, string surname, int gradeByBasicsOfAlgorithms);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRegistrationForOOPCourseContract/Registration")]
        System.Threading.Tasks.Task RegistrationAsync(int id, string surname, int gradeByBasicsOfAlgorithms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationForOOPCourseContract/IsStudentEnrolled", ReplyAction="http://tempuri.org/IRegistrationForOOPCourseContract/IsStudentEnrolledResponse")]
        bool IsStudentEnrolled(int id, string surname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationForOOPCourseContract/IsStudentEnrolled", ReplyAction="http://tempuri.org/IRegistrationForOOPCourseContract/IsStudentEnrolledResponse")]
        System.Threading.Tasks.Task<bool> IsStudentEnrolledAsync(int id, string surname);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegistrationForOOPCourseContractCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRegistrationForOOPCourseContract/ShowStudentsWithGreaterAvera" +
            "geBall")]
        void ShowStudentsWithGreaterAverageBall(System.Collections.Generic.List<RegistrationForCourseClient.RegistrationServiceReference.Student> students);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRegistrationForOOPCourseContract/ShowErrorMessage")]
        void ShowErrorMessage(string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRegistrationForOOPCourseContract/SetIdClient")]
        void SetIdClient(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegistrationForOOPCourseContractChannel : RegistrationForCourseClient.RegistrationServiceReference.IRegistrationForOOPCourseContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistrationForOOPCourseContractClient : System.ServiceModel.DuplexClientBase<RegistrationForCourseClient.RegistrationServiceReference.IRegistrationForOOPCourseContract>, RegistrationForCourseClient.RegistrationServiceReference.IRegistrationForOOPCourseContract {
        
        public RegistrationForOOPCourseContractClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public RegistrationForOOPCourseContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public RegistrationForOOPCourseContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrationForOOPCourseContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrationForOOPCourseContractClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Join() {
            base.Channel.Join();
        }
        
        public System.Threading.Tasks.Task JoinAsync() {
            return base.Channel.JoinAsync();
        }
        
        public void Leave(int id) {
            base.Channel.Leave(id);
        }
        
        public System.Threading.Tasks.Task LeaveAsync(int id) {
            return base.Channel.LeaveAsync(id);
        }
        
        public void Registration(int id, string surname, int gradeByBasicsOfAlgorithms) {
            base.Channel.Registration(id, surname, gradeByBasicsOfAlgorithms);
        }
        
        public System.Threading.Tasks.Task RegistrationAsync(int id, string surname, int gradeByBasicsOfAlgorithms) {
            return base.Channel.RegistrationAsync(id, surname, gradeByBasicsOfAlgorithms);
        }
        
        public bool IsStudentEnrolled(int id, string surname) {
            return base.Channel.IsStudentEnrolled(id, surname);
        }
        
        public System.Threading.Tasks.Task<bool> IsStudentEnrolledAsync(int id, string surname) {
            return base.Channel.IsStudentEnrolledAsync(id, surname);
        }
    }
}
